version: '3'

services:
  app:
    container_name: app_microframework
    build:
      context: .
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
    #network_mode: host #ao usar a rede da maquina host, nao ha necessidade de mapear as portas
  mysql:
    container_name: microdbmysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: appdados
      MYSQL_USER: appdados
      MYSQL_PASSWORD: 12345678
    ports:
      - "3309:3306"
    volumes:
      - micro-db-data:/var/lib/mysql
  
volumes:
  micro-db-data: